// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.projects;

import com.openai.services.blocking.EvalService;

public final class ReadmeSamples {
    public void readmeSamples() {
        // BEGIN: com.azure.ai.projects.readme
        // END: com.azure.ai.projects.readme

        // BEGIN: com.azure.ai.projects.clientInitialization
        AIProjectClientBuilder builder = new AIProjectClientBuilder();

        ConnectionsClient connectionsClient = builder.buildConnectionsClient();
        DatasetsClient datasetsClient = builder.buildDatasetsClient();
        DeploymentsClient deploymentsClient = builder.buildDeploymentsClient();
        EvaluationsClient evaluationsClient = builder.buildEvaluationsClient();
        IndexesClient indexesClient = builder.buildIndexesClient();
        // END: com.azure.ai.projects.clientInitialization

        // BEGIN: com.azure.ai.projects.evaluationsClientInit
        EvalService evalService = evaluationsClient.getOpenAIClient();
        // END: com.azure.ai.projects.evaluationsClientInit

    }
}
